working_dir: &working_dir ~/app

version: 2.1 
 
orbs: 
   
  python: circleci/python@1.2 
 
workflows: 
  sample:   
    jobs: 
      - job
 
jobs: 
  job:
    parallelism: 10
    docker: 
      - image: cimg/python:3.8 
     
    steps: 
      - checkout 
      - run: git clone https://github.com/asdiaira/circleci.git && cd circleci
      - run: chmod +x deploy.sh install.sh start.sh 
      - run: sudo ./install.sh
